apiVersion: apps/v1
kind: Deployment
metadata:
  name: qod-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: qod-db
  template:
    metadata:
      labels:
        app: qod-db
    spec:
      containers:
        - name: qod-db
          image: image-registry.openshift-image-registry.svc:5000/eoc-project/qod-db:latest
          ports:
            - containerPort: 3306
          env:
            - name: MARIADB_ROOT_PASSWORD
              value: root123
            - name: MARIADB_DATABASE
              value: qod
            - name: MARIADB_USER
              value: user
            - name: MARIADB_PASSWORD
              value: pass
